from __future__ import annotations

from typing import Protocol

from app.domain.entities.client import Client


class ClientRepository(Protocol):
    def create(self, client: Client) -> None: ...
    def update(self, client: Client) -> None: ...
    def get(self, client_id: str) -> Client | None: ...
    def find_by_name_or_tax_id(self, value: str) -> Client | None: ...
    def list(self) -> list[Client]: ...
