from __future__ import annotations

from typing import Protocol

from app.domain.entities.invoice import Invoice


class InvoiceRepository(Protocol):
    def create(self, invoice: Invoice) -> None: ...
    def update(self, invoice: Invoice) -> None: ...
    def get(self, invoice_id: str) -> Invoice | None: ...
    def list(self, status: str | None = None, year: int | None = None, client_id: str | None = None) -> list[Invoice]: ...
    def validate_invoice_integrity(self, invoice_id: str) -> bool: ...
